services:
#    macao_user.example:
#        class: Macao\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    macao_user.security.user_provider:
        class     : Macao\UserBundle\Security\Core\User\FOSUBUserProvider
        arguments : ['@fos_user.user_manager', '@doctrine.orm.entity_manager', '@validator', { google: google_id }, '@service_container']